# Development environment overrides
baseURL = ""
relativeURLs = true
canonifyURLs = false
disableLiveReload = false

# Development-specific settings
[params]
  # Disable CDN for local development
  cdn_url = ""
