import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import fs from "fs";
import path from "path";
import { INSIGHTS_SECTIONS, insightsCardPath } from "./src/insights/cards";
import { LEDGER_VIEWS, ledgerViewPath } from "./src/ledger/views";

// Returns an autogenerated sidebar item only when the directory exists.
// This makes the sidebar resilient to schemas that lack certain type categories
// (e.g. no interfaces or inputs in a simple domain model).
function autoDir(dirName: string) {
  const abs = path.join(__dirname, "docs", dirName);
  return fs.existsSync(abs) ? [{ type: "autogenerated" as const, dirName }] : [];
}

export const insightsSidebar = INSIGHTS_SECTIONS.map((section) => ({
  type: "category" as const,
  label: section.label,
  items: section.cards.map((card) => ({
    type: "link" as const,
    label: card.label,
    href: insightsCardPath(card.id),
  })),
}));

type LedgerLink = { type: "link"; label: string; href: string };
type LedgerCategory = { type: "category"; label: string; items: LedgerLink[] };

// A section opens a category and the views after it join the one above, so the
// order in LEDGER_VIEWS is the order the sidebar shows.
export const ledgerSidebar = LEDGER_VIEWS.reduce<(LedgerLink | LedgerCategory)[]>((items, view) => {
  const link: LedgerLink = {
    type: "link",
    label: view.label,
    href: ledgerViewPath(view.id),
  };
  if (view.section === null) {
    return [...items, link];
  }
  const last = items.at(-1);
  if (last?.type === "category" && last.label === view.section) {
    last.items.push(link);
    return items;
  }
  return [...items, { type: "category", label: view.section, items: [link] }];
}, []);

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    "elements/schema",
    {
      type: "category" as const,
      label: "Types",
      items: [
        {
          type: "category" as const,
          label: "Field Containers",
          items: [
            { type: "category" as const, label: "Objects", items: autoDir("elements/types/objects") },
            { type: "category" as const, label: "Interfaces", items: autoDir("elements/types/interfaces") },
            { type: "category" as const, label: "Inputs", items: autoDir("elements/types/inputs") },
          ].filter((c) => c.items.length > 0),
        },
        { type: "category" as const, label: "Enums", items: autoDir("elements/types/enums") },
        { type: "category" as const, label: "Scalars", items: autoDir("elements/types/scalars") },
        { type: "category" as const, label: "Queries", items: autoDir("elements/operations/queries") },
      ].filter((c) => "items" in c && (c.items as unknown[]).length > 0),
    },
    {
      type: "category" as const,
      label: "Other",
      items: [
        { type: "category" as const, label: "Directives", items: autoDir("elements/types/directives") },
      ].filter((c) => c.items.length > 0),
    },
  ],
  insightsSidebar,
  ledgerSidebar,
};

export default sidebars;
