# Overrides for production environment
# baseURL will be set by GitHub Actions
relativeURLs = false
canonifyURLs = true
disableLiveReload = true
enableRobotsTXT = true

# Ensure consistent URL generation
uglyURLs = false
removePathAccents = false
