# Overrides for production environment
baseURL = "/s2dm/"
relativeURLs = false
canonifyURLs = false
disableLiveReload = true
enableRobotsTXT = true

# Ensure consistent URL generation
uglyURLs = false
removePathAccents = false

# Asset processing
[params]
  cdn_url = "https://giaccomole.github.io/s2dm"
