baseURL = "https://covesa.github.io/s2dm"
languageCode = "en-us"
title = "S2DM"
theme = "hugo-theme-relearn"
publishDir = "../docs"
[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "green"
  disableInlineCopyToClipBoard = true
  disableLandingPageButton = true

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/covesa/s2dm"
weight = 10

# Generation of JSON index to allow search
[outputs]
home = ['html', 'rss', 'search', 'searchpage']

# So that raw HTML content is enabled in Hugo project

[markup.goldmark.renderer]
unsafe = true
