name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: uv
        uses: astral-sh/setup-uv@v4

      - name: sync
        run: |
          uv sync

      - name: pre-commit
        run: |
          uv run pre-commit run --all-files

      - name: mypy
        run: |
          uv run mypy src

      - name: test
        run: |
          uv run nox
